github:
  owner: getsentry
  repo: sentry-toolbar
preReleaseCommand: bash bin/bump-version.sh
targets:
  # Versioned CDN Bundle Target
  - name: gcs
    id: 'browser-cdn-bundles'
    includeNames: /.*\.js.*$/
    bucket: sentry-js-sdk
    paths:
      - path: /sentry-toolbar/{{version}}/
        metadata:
          cacheControl: 'public, max-age=60'
  # Latest CDN Bundle Target
  - name: gcs
    id: 'browser-cdn-bundles'
    includeNames: /.*\.js.*$/
    bucket: sentry-js-sdk
    paths:
      - path: /sentry-toolbar/latest/
        metadata:
          cacheControl: 'public, max-age=60'

  - name: commit-on-git-repository
    id: getsentry/sentry-toolbar
    archive: /^sentry-toolbar.tgz$/
    repositoryUrl: https://github.com/getsentry/sentry-toolbar.git
    stripComponents: 1
    branch: main
    createTag: true
